rest.api.base-url=http://localhost:8080
server.port=8081
rest.api.token=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2NDUzMTc1MCwiZXhwIjoxNzY0NjE4MTUwfQ.mjLgJtBQfntCYgV2PXfP_EwUEx2ieSFi0ldNSOC7sOkc6U_YG97dfIMpEeoPLBrN