rest.api.user-base-url=${USER_API_URL:http://localhost:8080}
rest.api.rent-base-url=${RENT_API_URL:http://localhost:8082}
server.port=8081

management.endpoints.web.exposure.include=health,info,circuitbreakers,retries
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userService.ignore-exceptions=org.springframework.web.client.HttpClientErrorException
resilience4j.retry.instances.userService.max-attempts=3
resilience4j.retry.instances.userService.wait-duration=500ms
resilience4j.retry.instances.userService.ignore-exceptions=org.springframework.web.client.HttpClientErrorException

resilience4j.circuitbreaker.instances.rentService.sliding-window-size=10
resilience4j.circuitbreaker.instances.rentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.rentService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.rentService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.rentService.ignore-exceptions=org.springframework.web.client.HttpClientErrorException
resilience4j.retry.instances.rentService.max-attempts=3
resilience4j.retry.instances.rentService.wait-duration=500ms
resilience4j.retry.instances.rentService.ignore-exceptions=org.springframework.web.client.HttpClientErrorException
