### Home
GET localhost:8080

### Pobierz użytkownika po username (getUserByUsername)
GET localhost:8080/api/v1/user/username/anna

### Pobierz użytkownika po ID (getUserById)
GET localhost:8080/api/v1/user/id/1

### Pobierz wszystkich użytkowników (getUsers)
GET localhost:8080/api/v1/users

### Utwórz nowego użytkownika CreateUserDTO (createUser)
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "username": "nowy",
  "name": "Nowy",
  "active": false
}

### Usuń użytkowników po ID (deleteUser)
DELETE localhost:8080/api/v1/user/id/4

### Aktywuj użytkownika
PATCH localhost:8080/api/v1/user/id/2/activate

### Dezaktywuj użytkownika
PATCH localhost:8080/api/v1/user/id/2/deactivate

### Wyszukaj użytkowników po fragmencie nazwy (searchUsers)
GET localhost:8080/api/v1/user/search/e

### Zmień nazwę użytkownika (rename)
PATCH localhost:8080/api/v1/user/id/3/rename
Content-Type: application/json

{
  "name": "NowaNazwa"
}
