spring.application.name=UserService
spring.data.mongodb.uri=mongodb://root:passwd@localhost:27017/pas_db?authSource=admin&serverSelectionTimeoutMS=10000
spring.data.mongodb.database=pas_db
spring.main.lazy-initialization=true
pas.mongodb.collection.users=users
jwt.expiration.ms=60000
jwt.refresh.expiration.ms=86400000
jwt.private-key=${JWT_PRIVATE_KEY:classpath:keys/private_key.pem}
jwt.public-key=${JWT_PUBLIC_KEY:classpath:keys/public_key.pem}
server.port=8080

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.mongo.enabled=true
management.metrics.tags.application=${spring.application.name}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.default-requeue-rejected=false
