spring.application.name=RentService
spring.data.mongodb.uri=mongodb://root:passwd@localhost:27017/rent_db?authSource=admin&serverSelectionTimeoutMS=10000
spring.data.mongodb.database=rent_db
spring.main.lazy-initialization=true
pas.mongodb.collection.clients=clients
pas.mongodb.collection.resources=resources
pas.mongodb.collection.allocations=allocations
jwt.secret=PodstawyAplikacjiSieciowychMegaTrudneIDlugieHaslo
jwt.expiration.ms=60000
jwt.refresh.expiration.ms=86400000
server.port=8082
